### ISSUE TITLE
3 more worlds for you

### ISSUE THREAD

**Issue by pearlhyacinth** [limbofeather/worlds#5]
include https://gallery.styly.cc/, https://arium.xyz/, https://www.tz1and.com/

**Comment by limbofeather** [comment]
Thanks for these - do you know if these have WebXR support, Multiplayer support and web3 support?

**Comment by limbofeather** [comment]
Here's the PR: https://github.com/limbofeather/worlds/pull/7/files

**Comment by pearlhyacinth** [comment]
styly is webxr - VR accessible - not crypto and no avatars - i think you might be able to be in there with others though - 
not sure

i have not played with arium yet but it seems to have an NFT focus in that you can display nfts - not sure much else 
about it yet

tzland does not have vr access - it is totally built on tezos ecosystem so everything that is placed is minted - it is 
multiplayer with simple avatars - very new world (last couple of months)

another web based one you don't have listed is new art city https://newart.city/ - not crypto - no vr - it is multiplayer but 
the avatars are just floating shapes

i listed the other links in the github

**Comment by limbofeather** [comment]
Thanks, I've taken into account your input and also added New Art City!

**Comment by limbofeather** [comment]
Here's the PR I'll merge: https://github.com/limbofeather/worlds/pull/7

**Comment by limbofeather** [comment]
Closing since issue has been addressed
